<a href="https://colab.research.google.com/github/MiliWerneck/Python_CEFET/blob/main/Aula_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.23

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.23/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [ ]:
import numpy

https://numpy.org/doc/1.23/reference/generated/numpy.arange.html

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

1.   Item da lista
2.   Item da lista

In [ ]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.23/user/basics.creation.html

In [ ]:
km = np.array([1000, 2300, 4987, 1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.23/user/basics.types.html

In [ ]:
km.dtype #Tipo inteiro padrão (igual o long no C)

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.23/reference/generated/numpy.loadtxt.html

In [ ]:
#criar arrays numpy a partir de dados externos
#fname = , que receve o nome do arquivo cujo conteúdo queremos armazenar
km = np.loadtxt(fname = '/content/drive/MyDrive/CEFET-MG Divinopolis/Superior/Programacao_em_python/Aula_16/Aula_16/carros-km.txt',dtype = int)

In [ ]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
km.dtype #define o tipo de dado armazenado

dtype('int64')

### Arrays com duas ou mais dimensões

In [ ]:
#funciona como uma matriz ou um dataset
dados = [
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
Acessorios = np.array(dados)

In [ ]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [ ]:
km.shape # é um vetor. Dimensao: possui 258 linhas

(258,)

In [ ]:
Acessorios.shape # é  uma matriz. Possui 3 linhas e 8 colunas.

(3, 8)

## Comparando desempenho com listas
### Em python existem várias coleções de dados, então porque utilizar NumPy?

In [ ]:
np_array = np.arange(1000000) #cria números até um milhão

In [ ]:
py_list = list(range(1000000)) #cria números até um milhão

In [ ]:
%time for _ in range(100): np_array *= 2 #verifica o tempo de execução desse código.

CPU times: user 61.6 ms, sys: 0 ns, total: 61.6 ms
Wall time: 61.9 ms


In [ ]:
%time for _ in range(100): py_list = [x * 2 for x in py_list] #verifica o tempo de execução desse código.

CPU times: user 11.2 s, sys: 2.26 s, total: 13.5 s
Wall time: 17.4 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
anos = [2003, 1991, 1990, 2019, 2006]
idade = 2019 - anos

TypeError: ignored

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
# subtração de um inteiro para cada elemento de um array Numpy
idade = 2023 - anos # retorna outro array Numpy contendo as idades de cada um dos veículos.

In [ ]:
idade

array([20, 32, 33,  4, 17])

### Operações entre arrays

In [ ]:
km_media = km / idade #divisão entre os elementos de cada array
'''
Existe uma divisão por zero, por isso a operação retorna um erro
Contudo, o próprio Numpy preenche esse valor com nan (not a number) e continua a
operação.
'''

<ipython-input-29-574c24da8e12>:1: RuntimeWarning: invalid value encountered in divide
  km_media = km / idade #divisão entre os elementos de cada array


'\nExiste uma divisão por zero, por isso a operação retorna um erro\nContudo, o próprio Numpy preenche esse valor com nan (not a number) e continua a\noperação.\n'

In [ ]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [ ]:
44410 / (2019 - 2003)

2775.625

In [ ]:
5712 / (2019 - 1991)

204.0

### Operações com arrays de duas dimensões

In [ ]:
dados = np.array([km, anos]) #array com duas dimensões (matriz)

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape #dimensão: 2 linhas e 5 coluna

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados[0] #acesso ao primeiro array/linha contendo 5 dados.

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1] #acesso ao segundo array/linha contendo 5 dados.

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
km_media = dados[0] / (2019 - dados[1])

<ipython-input-38-ba3d668d4f3e>:1: RuntimeWarning: invalid value encountered in divide
  km_media = dados[0] / (2019 - dados[1])


In [ ]:
(2019 - dados[1])

array([16., 28., 29.,  0., 13.])

In [ ]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [ ]:
contador = np.arange(10) # a indexação de um array Numpy inicia no 0
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[0] #acesso dos itens de um array pelo índice

0

In [ ]:
'''Como a indexação de um array Numpy inicia em 0, a posição de um elemento
desejado é obtida pela operação posicao - 1'''
posicao = 6
index = posicao -1
contador[index]

5

In [ ]:
contador[-1] #acessa o o último elemento do array

9

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [ ]:
#Selecionar itens de arrays multidimensional com dois pares de colchetes
dados[1][2] #dados[linha][coluna]

1990.0

In [ ]:
#Selecionar itens de arrays multidimensional com um par de colchetes e uma vírgula
dados[1,2] #dados[linha,coluna]

1990.0

 ### Fatiamentos

A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)

<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
'''
fatiamento em um array Numpy, onde 1 é o índice inicial;
e 4 é o índice de parada, o seu item não é incluso
'''
contador[1:4]

array([1, 2, 3])

In [ ]:
'''
fatiamento em um array Numpy, onde 1 é o índice inicial;
8 é o índice de parada;
e 2 é o indicador de passo, que deve ser diferente de 0
'''
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
'''
Pega todos os números pares do conjunto contador
Omiti os índices inicial e final, mantém somente o passo 2
'''
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
'''
Pega todos os números impares do conjunto contador
Omiti-se o índice final
'''
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
dados #Fatiamento com matrizes - linha 1: km; linha 2: ano de fabricação

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:] # recupera todas as linhas do array dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:, 1:3] #recupera todos os itens das colunas 1 e 2

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [ ]:
'''
Calcula a quilometragem média  de dois veículos:
- pega somente a primeira linha com o índice 0: as quilometragens de dois veículos
- subtrai 2019 pelos itens da segunda linha com o índice 1: Recupera-se a idade  de dois carros
'''
dados[:, 1:3][0] / (2019 - dados[:, 1:3][1])

array([ 204.        , 1280.10344828])

In [ ]:
dados[0] / (2019 - dados[1])

<ipython-input-59-fb26cb8e809a>:1: RuntimeWarning: invalid value encountered in divide
  dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
'''
Retorna True para os itens do conjunto que satisfazem a comparação
Retorna False para os itens do conjunto que não satisfazem a comparação
'''
contador > 5 # compara os intens do array contador com o escalar 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
'''
A expressão contador > 5 permite selecionar somente os elementos maiores do que 5
'''
contador[contador > 5] # retorna um array com os elementos que satisfazem a condição de teste

array([6, 7, 8, 9])

In [ ]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]  # retorna um array com os elementos que satisfazem a condição de teste

array([6, 7, 8, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[1] > 2000 # seleciona os anos dos veículos fabricados apos o ano 2000

array([ True, False, False,  True,  True])

In [ ]:
'''
Calcula a quilometragem média dos veículos fabricados apos o ano 2000
'''
dados[0, dados[1]>2000] / (2019 - dados[1, dados[1]>2000])

<ipython-input-66-a941c637fb81>:4: RuntimeWarning: invalid value encountered in divide
  dados[0, dados[1]>2000] / (2019 - dados[1, dados[1]>2000])


array([2775.625     ,           nan, 1981.30769231])

# 5.4 Atributos e métodos de arrays Numpy

In [ ]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

### Atributos

https://numpy.org/doc/1.23/reference/arrays.ndarray.html#array-attributes

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [ ]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [ ]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [ ]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [ ]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [ ]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [ ]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.23/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [ ]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5,2), order='C') #indexação da linguagem C,

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5,2), order='F') #indexaçãoda linguagem Fortran,

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
'''
- Transforma a lista em um array Numpy
- reshape((2,5)): Reorganiza:
    - 1ª linha representa a quilometragem;
    - 2ª represnta  ano de determinado carro.
'''
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
np.array(info_carros).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [ ]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados_new.resize((3, 5)) #Retorna um erro: dizendo que não é possivel redimensionar, pois não é possivel reorganizar dessa maneira

ValueError: ignored

In [ ]:
'''
refcheck=False: informa que o Numpy não deverá checar essas referências com erros
Come esse parâmetro, cria-se uma dimensão números 0
'''
dados_new.resize((3,5), refcheck=False)

In [ ]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [ ]:
dados_new[2] = dados[0] / (2019 - dados_new[1])

<ipython-input-87-a7fac3016504>:1: RuntimeWarning: invalid value encountered in divide
  dados_new[2] = dados[0] / (2019 - dados_new[1])


In [ ]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.23/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.23/reference/routines.statistics.html

e

https://numpy.org/doc/1.23/reference/routines.math.html

In [ ]:
anos = np.loadtxt(fname = "/content/drive/MyDrive/CEFET-MG Divinopolis/Superior/Programacao_em_python/Aula_16/Aula_16/carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "/content/drive/MyDrive/CEFET-MG Divinopolis/Superior/Programacao_em_python/Aula_16/Aula_16/carros-km.txt")
valor = np.loadtxt(fname = "/content/drive/MyDrive/CEFET-MG Divinopolis/Superior/Programacao_em_python/Aula_16/Aula_16/carros-valor.txt")

In [ ]:
anos.shape #quantidade de linhas

(258,)

https://numpy.org/doc/1.23/reference/generated/numpy.column_stack.html

In [ ]:
#Cria um único array, cujas colunas representam cada um dos arrays anteriores.
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [ ]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [ ]:
np.mean(dataset, axis=0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis=1)

array([44830.54666667, 37954.98      , 37315.05333333, 42189.35666667,
       40125.03333333, 36745.91      , 19488.06666667, 63972.81333333,
       73974.42333333, 38851.83      , 28836.19666667, 27992.84333333,
       68168.99666667, 18400.79333333, 56984.80666667, 59177.8       ,
       36526.53      , 30190.46333333, 33932.89666667, 39638.76666667,
       69780.79333333, 32194.46666667, 77867.61333333, 76878.21666667,
       41205.07      , 24462.03333333, 34386.25      , 35817.28      ,
       39298.42333333, 72268.23333333, 34289.06666667, 41477.39333333,
       26365.56333333, 33918.13333333, 50905.01      , 54959.84      ,
       17875.19666667, 41766.95666667, 25768.39333333, 34876.18      ,
       54475.06333333, 59333.43      , 29553.44666667, 75040.79666667,
       39881.91      , 22655.23333333, 52057.21666667, 31725.88333333,
       22240.03333333, 69567.49666667, 78571.96333333, 61600.27666667,
       69114.54333333, 58791.90333333, 31242.99666667, 51282.34333333,
      

In [ ]:
np.mean(dataset[:, 1])

44499.41472868217

In [ ]:
np.mean(dataset[:, 2])

98960.51310077519

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [ ]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [ ]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
dataset[:, 1].sum()

11480849.0

In [ ]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
np.sum(dataset[:, 2])

25531812.38